import requests
import json
import sys
import os

# Link Phase 2 ML module path
sys.path.append(os.path.abspath("../phase2/ml"))
from predict import predict_single_sample

OLLAMA_API_URL = "http://localhost:11434/api/generate"
MODEL_NAME = "llama3.2"

SYSTEM_PROMPT = """You are an air-gapped NOC Copilot for secure MPLS network operations.
Your job is to explain network failure predictions produced by a machine learning model to human operators.

STRICT ACCURACY RULES:
1. NEVER invent facts, metrics, or telemetry values not explicitly supplied in the input.
2. STRICTLY DISTINGUISH between facts, predictions, and hypotheses:
   - OBSERVED FACTS: Actual telemetry measurements provided.
   - ML PREDICTIONS: Outputs generated by the machine learning classification model.
   - HYPOTHESES: Probable root causes inferred logically from metrics (label clearly as hypotheses).
3. Do NOT claim a root cause is confirmed unless supplied metrics prove it without ambiguity.

Required Response Format (Use exact header names):
Predicted Issue: <Issue name>
Confidence: <Confidence percentage>
Risk: <Risk Score and Level>
Time-to-Impact: <Estimated timeframe>
Why: <Short explanation of why risk is elevated>
Evidence:
 - [Observed Fact] <Specific metric observation>
 - [Observed Fact] <Specific metric observation>
Probable Root Cause: [Hypothesis] <Logical underlying issue>
Affected Scope: <Site, Device, and Interface affected>
Recommended Actions:
 1. <Immediate mitigation step>
 2. <Follow-up diagnostic step>
Urgency: <CRITICAL | HIGH | MEDIUM | LOW>
"""

def generate_noc_report(telemetry, topology_info, model_name=MODEL_NAME):
    """
    Ingests telemetry and topology, executes Phase 2 ML prediction,
    and passes structured prompt context to local Ollama LLM.
    """
    # 1. Generate ML Prediction & Risk Score
    ml_output = predict_single_sample(telemetry)

    # 2. Construct Grounded Prompt
    user_prompt = f"""
NETWORK CONTEXT:
Site: {topology_info.get('site', 'NYC-HQ')}
Device: {topology_info.get('device', 'Edge-Router-01')}
Interface: {topology_info.get('interface', 'GigabitEthernet0/0/1')}

OBSERVED TELEMETRY METRICS:
- Interface Utilization: {telemetry.get('utilization_pct')}%
- Latency: {telemetry.get('latency_ms')} ms
- Jitter: {telemetry.get('jitter_ms')} ms
- Packet Loss: {telemetry.get('packet_loss_pct')}%
- Hardware Interface Errors: {telemetry.get('interface_errors')}
- BGP Route Flaps: {telemetry.get('bgp_flaps')}
- OSPF Adjacency Changes: {telemetry.get('ospf_changes')}
- IPSec Tunnel Health: {telemetry.get('tunnel_health_pct')}%
- Traffic Volume: {telemetry.get('traffic_mbps')} Mbps

ML PREDICTION OUTPUT:
- Predicted Issue: {ml_output['predicted_issue']}
- ML Confidence: {ml_output['confidence']}
- Computed Risk Score: {ml_output['risk_score']} / 100 ({ml_output['risk_level']})
- Estimated Time-to-Impact: {ml_output['time_to_impact']}

Analyze this data and generate the NOC Copilot report following the system instructions.
"""

    # 3. Payload for Local Ollama API
    payload = {
        "model": model_name,
        "system": SYSTEM_PROMPT,
        "prompt": user_prompt,
        "stream": False,
        "options": {
            "temperature": 0.1  # Low temperature ensures deterministic, non-creative output
        }
    }

    try:
        response = requests.post(OLLAMA_API_URL, json=payload, timeout=60)
        response.raise_for_status()
        result = response.json()
        return result.get("response", "Error: Empty response from Ollama.")
    except requests.exceptions.ConnectionError:
        return "ERROR: Cannot connect to Ollama. Ensure Ollama service is running (`ollama serve`)."
    except Exception as e:
        return f"ERROR: Failed to generate response from Ollama: {str(e)}"